spring:
  profiles:
    include:
      - db
      - auth
      - doc
  cloud:
    aws:
      credentials:
        access-key: ${AWS_ACCESS_KEY:default}
        secret-key: ${AWS_SECRET_KEY:default}
      region:
        static: ${AWS_REGION:default}
      s3:
        bucket: ${AWS_S3_BUCKET:default}
      stack:
        auto: false
  mail:
    host: smtp.gmail.com
    port: ${SMTP_PORT:0000}
    username: ${SMTP_USERNAME:default}
    password: ${SMTP_PASSWORD:default}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  thymeleaf:
    cache: true
    prefix: classpath:/templates/
logging:
  discord:
    webhook-url: ${DISCORD_WEBHOOK_URL:default}
    attendance-webhook-url: ${DISCORD_ATTENDANCE_WEBHOOK_URL:default}

white-list:
  name1: ${SERVER_PROD_IP:localhost}
  name2: ${SERVER_PROD_DOMAIN:localhost}
server:
  domain:
    dev: ${SERVER_DEV_DOMAIN:https://gdsc-knu.shop}